---
- name: Configure host
  hosts: localhost
  become: true
  vars:
    install_alacritty: true
    install_i3: true
    install_rxvt_unicode: true
    install_xterm: true

  pre_tasks:
    - name: Update package cache (Alpine Linux)
      tags: package-manager
      community.general.apk:
        update_cache: true
      when: ansible_distribution == "Alpine"

    - name: Update package cache (Debian, Pop!_OS)
      tags: package-manager
      ansible.builtin.apt:
        update_cache: true
      when: ansible_distribution in ["Debian", "Pop!_OS"]

  tasks:

  roles:
    - role: ../ansible-role-i3