---
- name: Install rxvt-unicode package
  tags: package,terminal-emulator
  become: true
  ansible.builtin.package:
    name: "{{ rxvt_unicode_package }}"
    state: present
  when: install_rxvt_unicode

- name: Remove rxvt-unicode package
  tags: package,terminal-emulator
  become: true
  ansible.builtin.package:
    name: "{{ rxvt_unicode_package }}"
    state: absent
  when: not install_rxvt_unicode